---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ethbaas-node1-pv
  labels:
    app: ethbaas-node1-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /media/ethbaas/node1
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: ethbaas-demo
 name: node1-pv
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Gi
 selector:
   matchLabels:
     app: ethbaas-node1-pv