apiVersion: v1
kind: Service
metadata:
  namespace: ethbaas-demo
  name: node1
  labels:
    node: node1
spec:
  selector:
    node: ethbaas-node1
  type: NodePort
  ports:
  - protocol: TCP
    targetPort: 8545
    nodePort: 30545
    port: 8545
    name: http
  - protocol: TCP
    targetPort: 8546
    port: 8546
    name: websoket
  - protocol: TCP
    targetPort: 30303
    port: 30303
    name: p2p1
  - protocol: UDP
    targetPort: 30303
    port: 30303
    name: p2p2